default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: breakable_toy_development

test:
  <<: *default
  database: breakable_toy_test

production:
  <<: *default
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
